# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7K3Ndo0dwxWXZ35lhfzLYVm8W0G-iJ_
"""

import pandas as pd
# Yuklangan fayl nomini o'zgartiring
df = pd.read_csv('titanic_data.csv')
print(df)

filtered_df = df[df['age'] > 30]
print(len(filtered_df))

filtered_df = df[df['sex'] == 'male']
print(len(filtered_df))

filtered_df = df[df['sex'] == 'female']
print(len(filtered_df))

filtered_df = df[df['alive'] == 'yes']
print(filtered_df)